apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vlhsxd1sa-go 
  janus-idp.io/tekton: vlhsxd1sa-go
  backstage.io/kubernetes-id: vlhsxd1sa-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vlhsxd1sa-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml