apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vlhsxd1sa-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:bf34b44e2f6f9adeee1e483c7f7d8b9d2be12af8@sha256:e9a511f46934d9b3b7de35b1d3ceb1d2bff49e3ca03636852f72f129f87667cf
          name: container-image
